/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.ups.edu.vista;

import ec.ups.edu.controlador.ControladorTelefono;
import ec.ups.edu.controlador.ControladorUsuario;
import ec.ups.edu.dao.TelefonoDAOImpl;
import ec.ups.edu.dao.UsuarioDAOImpl;
import ec.ups.edu.modelo.Telefono;
import ec.ups.edu.modelo.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Adolfo
 */
public class VentanaTelefono extends javax.swing.JFrame {

    private UsuarioDAOImpl usuarioDao = new UsuarioDAOImpl();
    private TelefonoDAOImpl telefonoDao = new TelefonoDAOImpl();

    private ControladorUsuario controlador = new ControladorUsuario(usuarioDao, telefonoDao);
    private Telefono telefono;
    private Usuario usuario;

    private ControladorTelefono contro = new ControladorTelefono(telefonoDao);

    // private VentanaInicioSesion venta = new VentanaInicioSesion();
    /**
     * Creates new form VentanaTelefono
     */
    public VentanaTelefono(Usuario usuario) {
        initComponents();
        setLocation(425, 200);
        this.usuario = usuario;

    }

    public void crearTelefono(Usuario usuario) {

        /* telefono = this.telefono();
        controlador.crearTelefono(usuario, telefono);*/
        Usuario usu = usuario;
        int codigo2 = Integer.parseInt(txtCodigo.getText());

        telefono = contro.encontrarTelefono(codigo2);

        controlador.crearTelefono(usuario, telefono);
        
        JOptionPane.showMessageDialog(this, "Teléfono creado exitosamente");
    }

    public void telefono() {
        String numero1 = txtNumero.getText();
        String operadora1 = txtOperadora.getText();
        String tipo1 = txtTipo.getText();
        int codigo1 = Integer.parseInt(txtCodigo.getText());

        telefono = new Telefono(codigo1, numero1, tipo1, operadora1);
        contro.crearTelefono(telefono);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        panelDatos = new javax.swing.JPanel();
        numero = new javax.swing.JLabel();
        operadora = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtOperadora = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        panelBoton = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Telefono");

        mensaje.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        mensaje.setText("Bienvenido");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(mensaje)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Teléfono", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Georgia", 0, 14))); // NOI18N

        numero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        numero.setText("Número de teléfono:");

        operadora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        operadora.setText("Operadora:");

        tipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tipo.setText("Tipo de teléfono:");

        codigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        codigo.setText("Código del teléfono:");

        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumero.setText("0984871270");

        txtOperadora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOperadora.setText("Movistar");
        txtOperadora.setToolTipText("");

        txtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipo.setText("Celular");

        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.setText("1");

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero)
                    .addComponent(codigo)
                    .addComponent(tipo)
                    .addComponent(operadora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(txtOperadora)
                    .addComponent(txtTipo)
                    .addComponent(txtCodigo))
                .addGap(41, 41, 41))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operadora)
                    .addComponent(txtOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnCrear.setBackground(new java.awt.Color(153, 153, 255));
        btnCrear.setText("Crear Teléfono");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(153, 153, 255));
        btnListar.setText("Listar Teléfonos");

        javax.swing.GroupLayout panelBotonLayout = new javax.swing.GroupLayout(panelBoton);
        panelBoton.setLayout(panelBotonLayout);
        panelBotonLayout.setHorizontalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnListar)
                .addGap(55, 55, 55))
        );
        panelBotonLayout.setVerticalGroup(
            panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnListar))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:

        String num = txtNumero.getText();
        String operadora1 = txtOperadora.getText();
        String tipo1 = txtTipo.getText();
        String codigo1 = txtCodigo.getText();

        if (num == null || operadora1 == null || tipo1 == null || codigo1 == null) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        } else {
            System.out.println("\nhhh" + usuario);
            this.telefono();
            this.crearTelefono(usuario);
            
            System.out.println("\n" + usuario);
            /* VentanaInicioSesion ven = new VentanaInicioSesion();           
            ven.agregarTelefono();
            
            controlador.crearTelefono(telefono);
            
            controlador.iniciarSesion(codigo, operadora)
            controlador.imprimirTelefonos();*/
        }


    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel numero;
    private javax.swing.JLabel operadora;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JLabel tipo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOperadora;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables

}
